{
  "title": "Deploying MERN with Docker",
  "date": "2025-01-15",
  "tags": ["MERN", "Docker", "AWS", "DevOps"],
  "content": "<h1>Deploying a MERN Stack Application with Docker</h1><p>This post demonstrates how to containerize a MERN (MongoDB, Express, React, Node.js) application using Docker for rapid development and easy deployment on AWS.</p><img src=\"https://images.unsplash.com/photo-1605379399642-870262d3d051?w=800&h=400&fit=crop\" alt=\"MERN Docker Deployment\" /><h2>Prerequisites</h2><ul><li>Node.js and npm installed</li><li>Docker and Docker Compose installed</li><li>Basic understanding of MERN stack</li></ul><h2>Project Structure</h2><pre><code>mern-app/\n├── client/          # React frontend\n│   ├── Dockerfile\n├── server/          # Node.js backend\n│   ├── Dockerfile\n├── docker-compose.yml</code></pre><h2>Sample Dockerfile (Frontend)</h2><pre><code># client/Dockerfile\nFROM node:18-alpine as build\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\nRUN npm run build\nFROM nginx:alpine\nCOPY --from=build /app/build /usr/share/nginx/html\nEXPOSE 80\nCMD [\"nginx\", \"-g\", \"daemon off;\"]</code></pre><h2>Sample Dockerfile (Backend)</h2><pre><code># server/Dockerfile\nFROM node:18-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\nEXPOSE 5000\nCMD [\"node\", \"server.js\"]</code></pre><h2>Docker Compose Configuration</h2><pre><code>version: '3.8'\nservices:\n  frontend:\n    build: ./client\n    ports:\n      - \"3000:80\"\n    depends_on:\n      - backend\n  backend:\n    build: ./server\n    ports:\n      - \"5000:5000\"\n    environment:\n      - MONGO_URI=mongodb://mongodb:27017/mernapp\n    depends_on:\n      - mongodb\n  mongodb:\n    image: mongo:5.0\n    ports:\n      - \"27017:27017\"\n    volumes:\n      - data:/data/db\nvolumes:\n  data:</code></pre><h2>Pushing to AWS ECR</h2><ol><li>
Login to ECR:
<pre><code>aws ecr get-login-password | docker login --username AWS --password-stdin &lt;account_id&gt;.dkr.ecr.&lt;region&gt;.amazonaws.com</code></pre></li><li>
Build and push your images:
<pre><code>docker build -t mern-frontend ./client\ndocker tag mern-frontend &lt;ECR_URI&gt;/mern-frontend:latest\ndocker push &lt;ECR_URI&gt;/mern-frontend:latest</code></pre></li></ol>
<img src=\"https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=400&fit=crop\" alt=\"Docker Dashboard\" /><h2>Conclusion</h2><p>With Docker, deploying a full-stack MERN app becomes manageable, reproducible, and simple to scale up. You can use AWS ECS or EC2 to orchestrate these containers and take advantage of managed services.</p><blockquote><strong>Tip:</strong> Always use environment variables for secrets. Avoid hardcoding credentials in your Dockerfiles or code.</blockquote><h2>Demo Video</h2><video controls width=\"100%\"><source src=\"https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_2mb.mp4\" type=\"video/mp4\">Your browser does not support the video tag.</video><h2>Useful Links</h2><ul><li><a href=\"https://github.com/docker/awesome-compose\" target=\"_blank\">Awesome Docker Compose Examples</a></li><li><a href=\"https://docs.aws.amazon.com/AmazonECR/latest/userguide/what-is-ecr.html\" target=\"_blank\">AWS ECR Docs</a></li></ul>"
}
